### PR TITLE
Add related command in approve CSR of new registered cluster

### PR DESCRIPTION
**Pull request by wangglbj**
Hi @skeeey  Switch to hub context before get csr and  and adjust the order of instructions "kubectl get managedcluster“.
could you help to  review this.  many thanks.

### CODE REVIEW

**Comment by skeeey** [comment]
@wangglbj it looks good to me, would you squash your two comments, thanks

**Comment by wangglbj** [comment]
@skeeey Thanks for your quick reply. you konw, a user who is familiar with OCM may know to go to the hub, but for a person who does not know about OCM, if he does not go to the hub, he will not get to csr, and he will not go to approve csr.

**Comment by zhiweiyin318** [comment]
@wangglbj  please squash your 2 commits into 1 commit, it will keep the commit history clean. thanks.

**Pull request closed without merging**
