### PR TITLE
Update file name to reflect the change in Makefile

### PR DESCRIPTION
**Pull request by leipanhz**
Addressed reviewer's comments

/assign @zhiweiyin318
/assign @zhujian7

### CODE REVIEW

**Comment by zhujian7** [comment]
Could you also help rename the file `test/integration/klusterlet_detached_test.go` to `klusterlet_hosted_test.go`?
And please signoff your commit. `git commit --signoff ...`

**Comment by xuezhaojun** [comment]
Hello, @yitiangf, Thanks for your input👍. Kindly remind a GitHub tip: we can continue to push commits to the branch and GitHub will automatically sync the latest changes to the PR. We don't need to open other PR.

**Comment by xuezhaojun** [comment]
> Could you also help rename the file `test/integration/klusterlet_detached_test.go` to `klusterlet_hosted_test.go`? And please signoff your commit. `git commit --signoff ...`

Yes, you can use `git commit -s --amend` to sign your previous commit. and use `git push -f` to force push signed commit override your unsiged commit.

**Comment by xuezhaojun** [comment]
You can use the following comment to assign PR to others:

/assign @zhujian7 

Our CICD bot will automatically assign this PR based on `/assign`.

And to merge this PR: you need a lgtm and a approve.

Anyone could give a LGTM, but only approvers can give an approved tag.

You can find approvers in [OWNERS](https://github.com/open-cluster-management-io/registration-operator/blob/main/OWNERS), I recommend you assign qiujian16 and zhiweiyin318 for this repo.

**Comment by leipanhz** [comment]
> Could you also help rename the file `test/integration/klusterlet_detached_test.go` to `klusterlet_hosted_test.go`? And please signoff your commit. `git commit --signoff ...`

@zhujian7 I have made changes accordingly and updated the PR

**Pull request merged**
