### PR TITLE
upgrade operator-sdk to 1.0.1 and olm to 0.16.1

### PR DESCRIPTION
**Pull request by zhiweiyin318**

### CODE REVIEW

**Comment by RainbowMango** [comment]
Does this PR intend to fix https://github.com/open-cluster-management/registration-operator/issues/87?

**Comment by zhiweiyin318** [comment]
> Does this PR intend to fix #87?

@RainbowMango upgrading OLM can fix issue #87.

**Comment by qiujian16** [comment]
/approve
/lgtm

Thanks!

**Pull request merged**
