### PR TITLE
create migration requests for clusterset api

### PR DESCRIPTION
**Pull request by elgnay**
The related task: https://github.com/open-cluster-management/backlog/issues/16156
Signed-off-by: Yang Le <yangle@redhat.com>

### CODE REVIEW

**Review by qiujian16 — COMMENTED** [review]
could we move these to a different controllers (CRD migration controller)? We only need this in one release, and I would want the code to be separated.

**Comment by elgnay** [comment]
> could we move these to a different controllers (CRD migration controller)? We only need this in one release, and I would want the code to be separated.

A separated controller is created for CRD migration.

**Pull request merged**
