### PR TITLE
add podAntiAffinity for pods

### PR DESCRIPTION
**Pull request by zhiweiyin318**
support anti-affinity rules for availability zones.
related issue https://github.com/open-cluster-management/backlog/issues/2720

### CODE REVIEW

**Comment by pmorie** [comment]
Looks like a failure of the loopback e2e, possibly a flake.

/retest

**Comment by pmorie** [comment]
This looks good, but I want a clean e2e run before I tag lgtm

**Comment by zhiweiyin318** [comment]
failed by no lease role, I will rebase the code after the PR https://github.com/open-cluster-management/registration-operator/pull/39 is merged.
```
 Status: "Failure",
              Message: "leases.coordination.k8s.io \"cluster-lease-loopback-e2e-rd9pml\" not found",
              Reason: "NotFound",
```

**Pull request merged**
