### PR TITLE
Split Install of Operator and CR into 2 steps

### PR DESCRIPTION
**Pull request by zkayyali812**
This PR is to split the installation make targets into 2 optional targets.
- First to install the operator
- Second to apply the CR 

We aim to include the registration operator in our installer, and would prefer if we could separate this logic into the above steps to better fit our install processes.

--
This PR will allow us to install the operator, without installing the CR, so we can later drive the installation of the CR. This would only be for developer consumption.

### CODE REVIEW

**Review by nathanweatherly — APPROVED** [review]

**Comment by qiujian16** [comment]
@pmorie not quite sure why lgtm label is added, but i think we can use this pr to trigger postsubmit when build-harness is ready.

**Comment by pmorie** [comment]
> not quite sure why lgtm label is added

Nathan approved the PR in the github UX, which is translated into lgtm tag if someone is in the org or a collaborator afaik.

**Pull request merged**
